### PR TITLE
Friendship v2 feature

### PR DESCRIPTION
**Pull request by GabrielJSuarez**
Friendship V2 change list:

- Change the way that friend requests queries are handled
- Implement a double row friendship confirmation match
- Change the way that friend request/friend acceptance is shown in the views
- Change almost all the Rspec test suite to reflect the new changes

### CODE REVIEW

**Review by MahmoudBakr23 — CHANGES_REQUESTED** [review]
# **Changes Required ♻🛑**

<hr>

Hello there, nice work you've done so far on this milestone. However, there are still some mandatory changes you need to make in order to get it approved!

<hr>

- [x] Please make a more descriptive Pull Request body
- [x] Friendships table should contain a confirmed column to insure the confirmed and rejected friendships requests (see snippet below)
- [x] when friendship is confirmed, an additional row with reversed user-friend pair is created
```ruby
# Friendship model

def confirm_friend
  self.update_attributes(confirmed: true)
  Friendship.create!(friend_id: self.user_id,
                  user_id: self.friend_id,
                  confirmed: true)
end
```

- [x] In the user model, you should use the confirmed column to define the pending friendship requests, the confirmed, and the inverted_friendships
```ruby
# User model

has_many :confirmed_friendships, -> { where confirmed: true }, class_name: "Friendship"
has_many :friends, through: :confirmed_friendships
```
```ruby
# User model

# Users who needs to confirm friendship
has_many :pending_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "user_id"
has_many :pending_friends, through: :pending_friendships, source: :friend
```
```ruby
# User model

# Users who requested to be friends (needed for notifications)
has_many :inverted_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "friend_id"
has_many :friend_requests, through: :inverted_friendships
```

- [x] When I accept a friend request, it's duplicating the friend's username in the FRIENDSHIPS page (see image below)
Screenshot


<hr>

Kindly make sure to apply these changes before submitting for another re-review

Good luck and happy coding 👨‍💻💻

**Review by enaburekhan — CHANGES_REQUESTED** [review]
# Status: Request changes:full_moon:
**Great job on implementing most of the changes requested by the previous Tse:clap::clap:. However, there are still a few changes we need to make in order to get this project approved :muscle:.**
**Mandatory changes**

- [x] As highlighted by the previous Tse, make the PR more descriptive so that it can look professional. see screenshots [here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/) to serve as a guide.

- [x] Two of the test are failing on Rspec. Kindly fix it. see screen-shot: image

Make the requested changes and when you are done, kindly request for another review.

You can reach me on slack @ Eric Enaburekhan if you have any questions.
Happy Coding :blush:
Eric Enaburekhan.

**Review by Temmarie — CHANGES_REQUESTED** [review]
## Changes Required! :recycle:

### Hi @GabrielJSuarez  ! :wave: :wave:

#### You have done well so far :clap: However, there is just one little change required for you to make in order for this project to be approved. Kindly work on it and submit it for another code review.


**Recommended**

- [ ] You have one more Rspec test that's failing.

image


__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

**Review by cristianCeamatu — APPROVED** [review]
### 🥇 APPROVED 🥇

Congratulations and good luck with the next projects!

If you ever need any help or notice that you are wasting too many hours on a bug don't hesitate to contact me on Slack.

Best regards,
Cristian Ceamatu
Slack: Cristian Viorel Ceamatu

**Pull request merged**
